apiVersion: v1
kind: Namespace
metadata:
  name: better-wellness

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  namespace: better-wellness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: 750471540463.dkr.ecr.eu-north-1.amazonaws.com/profile-service:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Colombo
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "512Mi"
              cpu: "250m"    
      automountServiceAccountToken: false   
      imagePullSecrets:
            - name: aws-ecr

---

apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: better-wellness
spec:
  selector:
    app: profile-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: LoadBalancer
